version: '3.8'

services:
  db:
    image: postgres
    container_name: postgresrabbit
    environment:
      POSTGRES_USER: use
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: rabbit
    ports:
      - "5454:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      
  orchestrator:
    build: ./orchestrator
    container_name: orchestrator
    ports:
      - "8003:8003"
    depends_on:
      - db
      - rabbitmq
    environment:
      - DATABASE_URL=postgresql://use:pwd@db/orchestrator
      - RABBITMQ_HOST=rabbitmq
      - PORT=8003

volumes:
  pgdata: