version: '3.8'

services:
  db:
    image: postgres
    container_name: postgreskafka
    environment:
      POSTGRES_USER: use
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: kaf
    ports:
      - "6666:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
      
  # orchestrator:
  #   build: ./orchestrator
  #   container_name: orchestrator
  #   environment:
  #     - KAFKA_BROKER=kafka:9092
  #     - ORCHESTRATOR_PORT=8003
  #   ports:
  #     - '8003:8003'
  #   depends_on:
  #     - kafka
      
volumes:
  pgdata: